article/urls.py
from django.conf.urls import url
from article import views

urlpatterns = [
    url(r'^basics/(?P<cid>\d*)/$',views.BasicsView.as_view(),name='basics'),
    url(r'^detail/(?P<aid>\d*)/$', views.ArticleDetailView.as_view(), name='detail'),

]

blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from article import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/',include('tinymce.urls')),
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^article/',include('article.urls',namespace='article')),
]

article/models.py
from django.db import models
from tinymce.models import HTMLField

class Category(models.Model):
    CATEGORY =(
        (1,'Python基础'),
        (2,'数据库'),
        (3,'Django'),
        (4,'碎言碎语'),
        (5,'源码分享'),
        (6,'学无止境'),
    )
    name = models.SmallIntegerField(choices=CATEGORY,verbose_name='文章分类')

    class Meta:
        verbose_name = '文章分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.get_name_display()


class TagsModel(models.Model):
    name = models.CharField(max_length=10,default=None,null=True,verbose_name='类别标签')
    category = models.ForeignKey(Category,default=None,null=True,verbose_name='文章分类')

    class Meta:
        verbose_name = '类别标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class ArticleModel(models.Model):
    title = models.CharField(max_length=50,verbose_name='文章标题')
    content = HTMLField(verbose_name='文章内容')
    description = models.CharField(max_length=120,null=True,default=None,verbose_name='文章描述')
    image = models.ImageField(upload_to='article',null=True,default=None,verbose_name='图片')
    create_time = models.DateField(auto_now_add=True,verbose_name='创建时间')
    modify_time = models.DateField(auto_now=True,verbose_name='修改时间')
    click_count = models.IntegerField(default=0,verbose_name='点击量')
    category = models.ForeignKey(Category,verbose_name='文章类别')
    tags = models.ForeignKey(TagsModel,default=None,null=True,verbose_name='文章标签')

    class Meta:
        verbose_name = '我的文章'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

article/views.py
from django.shortcuts import render
from django.views import View
from .models import ArticleModel,Category,TagsModel

class IndexView(View):
    def get(self,request):
        article_list = ArticleModel.objects.filter().order_by('-id').all()
        return render(request,'index.html',locals())

class BasicsView(View):
    def get(self,request,cid):
        tid = request.GET.get('tid')
        article_list = ArticleModel.objects.filter(category_id=cid).order_by('-create_time').all()
        if tid:
            article_list = ArticleModel.objects.filter(category_id=cid,tags_id=tid).order_by('-create_time').all()
        category = Category.objects.filter(pk=cid).first()
        tags = TagsModel.objects.filter(category=category).all()
        return render(request,'basics.html',locals())


class ArticleDetailView(View):
    def get(self,request,aid):
        article = ArticleModel.objects.filter(pk=aid).first()
        return render(request, 'article_detail.html', locals())

templates/article_detail.html
{% extends 'base.html' %}
{% load static %}
{% block article %}
<article>
  <div class="container">
      <div id="art_title"><h2><b>{{ article.title }}</b></h2></div>
      <div id="art_content">{{ article.content|safe }}</div>

  </div>
  </aside>
</article>
{% endblock article %}

templates/base.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
    {% load static %}
<title>E·小星个人博客</title>
<meta name="keywords" content="E·小星个人博客" />
<meta name="description" content="E·小星个人博客" />
<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
<link href="{% static 'css/base.css' %}" rel="stylesheet">
<link href="{% static 'css/index.css' %}" rel="stylesheet">
<link href="{% static 'css/learn.css' %}" rel="stylesheet">
<link href="{% static 'css/mycss.css' %}" rel="stylesheet">
<!--[if lt IE 9]>
<script src="{% static 'js/modernizr.js' %}"></script>
<![endif]-->
<script src="{% static 'js/scrollReveal.js' %}"></script>
</head>
<body>
<header>
  <div class="logo" data-scroll-reveal="enter right over 1s"><a href="/"><img src="{% static 'images/logo.png' %}"></a></div>
  <nav class="topnav" data-scroll-reveal="enter bottom over 1s after 1s">
      <a href="{% url 'index' %}"><span>首页</span><span class="en">Home</span></a>
      {% for category in categorys %}
      <a href="{% url 'article:basics' category.id %}"><span>{{ category.get_name_display}}</span><span class="en">{{ category.get_name_display }}</span></a>
      {% endfor %}
{#      <a href="{% url 'article:databases' %}"><span>数据库</span><span class="en">Database</span></a>#}
{#      <a href="{% url 'article:django' %}"><span>Django</span><span class="en">Django</span></a>#}
{#      <a href="{% url 'article:doing' %}"><span>碎言碎语</span><span class="en">Doing</span></a>#}
{#      <a href="{% url 'article:share' %}"><span>源码分享</span><span class="en">Share</span></a>#}
{#      <a href="{% url 'article:learn' %}"><span>学无止境</span><span class="en">Learn</span></a>#}
  </nav>
</header>
{% block article %}
{% endblock article %}
<footer>
Design by DanceSmile <a href="/">蜀ICP备11002373号-1</a>
</footer>
<script>
	if (!(/msie [6|7|8|9]/i.test(navigator.userAgent))){
		(function(){
			window.scrollReveal = new scrollReveal({reset: true});
		})();
	};
</script>
</body>
</html>

templates/basics.html
{% extends 'base.html' %}
{% load static %}
{% block article %}
<article>
  <div class="container">
      <h2 class="ctitle"><b>{{category.get_name_display }}</b> <span>不要轻易放弃。学习成长的路上，我们长路漫漫，只因学无止境。</span></h2>
      <div class="rnav">
      <ul>
          {% for tag in tags %}
        <li><a href="{% url 'article:basics' cid %}?tid={{ tag.id }}">{{ tag.name }}</a></li>
          {% endfor %}
{#        <li><a href="">IP查询</a></li>#}
{#        <li><a href="">CSS3|Html5</a></li>#}
{#        <li><a href="">网站建设</a></li>#}
{#        <li><a href="">JS经典实例</a></li>#}
{#        <li><a href="">推荐工具</a></li>#}
      </ul>
    </div>
      <ul class="cbp_tmtimeline">
                    {% for article in article_list %}
					<li>
						<time class="cbp_tmtime"><span>{{ article.create_time|date:'m-d' }}</span> <span>{{ article.create_time|date:'Y' }}</span></time>
						<div class="cbp_tmicon"></div>
						<div class="cbp_tmlabel" data-scroll-reveal="enter right over 1s" >
							<h2>{{ article.title}}</h2>
							 <p><span class="blogpic"><a href="{% url 'article:detail' article.id%}"><img src="{{ MEDIA_URL }}{{ article.image }}"></a></span>{{ article.description }}</p>
                             <a href="{% url 'article:detail' article.id%}" target="_blank" class="readmore">阅读全文&gt;&gt;</a>
						</div>
					</li>
                    {% endfor %}


				</ul>

      <div class="page"><a title="Total record"><b><<</b> </a><b>1</b><a href="">2</a><a href="">3</a><a href="">4</a><a href="">5</a><a href="">&gt;&gt;</a></div>
  </div>
  </aside>
</article>
{% endblock article %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block article %}
<article>
  <div class="container">
    <div class="blog" data-scroll-reveal="enter top" >
      <figure>
        <ul>
          <a href="/"><img style="width: 270px;height: 256px" src="{% static 'images/article/thread.jpg' %}"><span>阅读全文</span></a>
        </ul>
        <p><a href="/">并发编程</a></p>
        <figcaption>所谓并发编程是指在一台处理器上“同时”处理多个任务。并发是在同一实体上的多个事件。多个事件在同一时间间隔发生...</figcaption>
      </figure>
      <figure>
        <ul>
          <a href="/"><img style="width: 270px;height: 256px" src="{% static 'images/article/python.jpg' %}"><span>阅读全文</span></a>
        </ul>
        <p><a href="/">python之美</a></p>
        <figcaption>Python是一种代表简单主义思想的语言。阅读一个良好的Python程序就感觉像是在读英语一样。它使你能够专注于解决问题而不是去搞明白语言本身...</figcaption>
      </figure>
      <figure>
        <ul>
          <a href="/"><img style="width: 270px;height: 256px"  src="{% static 'images/article/databases.jpg' %}"><span>阅读全文</span></a>
        </ul>
        <p><a href="/">MySQL</a></p>
        <figcaption>MySQL是一个关系型数据库管理系统，由瑞典MySQL AB 公司开发，目前属于 Oracle 旗下产品。MySQL 是最流行的关系型数据库管理系统之一...</figcaption>
      </figure>
    </div>
   <ul class="cbp_tmtimeline">
       {% for article in article_list %}
					<li>
						<time class="cbp_tmtime"><span>{{ article.create_time|date:'m-d'}}</span> <span>{{ article.create_time|date:'Y'}}</span></time>
						<div class="cbp_tmicon"></div>
						<div class="cbp_tmlabel" data-scroll-reveal="enter right over 1s" >
							<h2>{{ article.title }}</h2>
							 <p><span class="blogpic"><a href="/"><img style="width: 200px;height: 120px"  src="{{ MEDIA_URL }}{{ article.image }}"></a></span>{{article.description}}</p>
                             <a href="{% url 'article:detail' article.id %}" target="_blank" class="readmore">阅读全文&gt;&gt;</a>
						</div>
					</li>
       {% endfor %}
				</ul>
  </div>
</article>
{% endblock article %}